---
शीर्षक: analogWrite()
श्रेणियाँ: [ "कार्यों" ]
उपश्रेणियों: [ "एनालॉग आई/ओ" ]
---





= analogWrite()


// अवलोकन अनुभाग शुरू होता है
[#अवलोकन]
--

[float]
=== विवरण
एक पिन करने के लिए एक अनुरूप (http://arduino.cc/en/Tutorial/PWM[PWM wave]) मूल्य लिखता है। अलग-अलग चमक पर एक एलईडी प्रकाश करने या विभिन्न गति से मोटर चलाने के लिए इस्तेमाल किया जा सकता है। `analogWrite()` के लिए एक कॉल के बाद, अगली कॉल `analogWrite()` (या `digitalRead()` या `digitalWrite()`) के लिए अगली कॉल तक पिन निर्दिष्ट कर्तव्य चक्र की एक स्थिर वर्ग तरंग उत्पन्न करेगा। उसी पिन पर| 
[options="header"]
|====================================================================================================
| बोर्ड                                    | PWM पिन                        | PWM आवृत्ति
| उनो (UNO), नैनो (Nano), मिनी (Mini)      | 3, 5, 6, 9, 10, 11              | 490 Hz (पिन 5 और 6: 980 Hz)
| मेगा (Mega)                             | 2 - 13, 44 - 46                 | 490 Hz (पिन 4 और 13: 980 Hz)
| लेओनार्दो (Leonardo), माइक्रो (Micro), Yún  | 3, 5, 6, 9, 10, 11, 13          | 490 Hz (पिन 3 और 11: 980 Hz)
| Uno WiFi Rev.2                         | 3, 5, 6, 9, 10                  | 976 Hz
| एमकेआर (MKR) बोर्ड्स *                   | 0 - 8, 10, A3 (18), A4 (19)     | 732 Hz
| MKR1000 WiFi *                         | 0 - 8, 10, 11, A3 (18), A4 (19) | 732 Hz
| जीरो (Zero) *                           | 3 - 13, A0 (14), A1 (15)        | 732 Hz
| ड्यू (Due) **                            | 2-13                            | 1000 Hz
| 101                                    | 3, 5, 6, 9                      | पिन 3 और 9: 490 Hz, पिन 5 और 6: 980 Hz
|====================================================================================================
{empty}* उपरोक्त उल्लिखित पिनों पर PWM क्षमताओं के अलावा, एमकेआर और ज़ीरो बोर्डों का `DAC0` (`A0`) पिन पर `analogWrite()` का उपयोग करते समय सही एनालॉग आउटपुट है।. +
{empty}** उपरोक्त उल्लिखित पिंस पर PWM क्षमताओं के अलावा, ड्यू का `DAC0` और `DAC1` पर `analogWrite()` का उपयोग करते समय ड्यू का सही एनालॉग आउटपुट होता है।.

[%hardbreaks]

`analogWrite ()` कहने से पहले पिन को आउटपुट के रूप में सेट करने के लिए आपको `pinMode ()` को कॉल करने की आवश्यकता नहीं है।
The `analogWrite` function has nothing to do with the analog pins or the `analogRead` function.
[%hardbreaks]


[float]
=== वाक्य - विन्यास (Syntax)
`analogWrite(pin, value)`


[float]
=== पैरामीटर
`pin`: Arduino पिन को लिखने के लिए। अनुमत डेटा प्रकार: `int`। +
`value`: कर्तव्य चक्र: 0 (हमेशा बंद) और 255 (हमेशा) के बीच। अनुमत डेटा प्रकार: `int`.


[float]
=== रिटर्न
Nothing

--
// ओवरव्यू अनुभाग अंत




// कैसे उपयोग करें खंड की शुरुआत
[#howtouse]
--

[float]
=== उदाहरण कोड
पोटेंशियोमीटर से पढ़े जाने वाले मूल्य के लिए आनुपातिक एलईडी आउटपुट को सेट करता है|


[source,arduino]
----
int ledPin = 9;      // एलईडी डिजिटल पिन 9 से जुड़ा है
int analogPin = 3;   // पोटेंशियोमीटर एनालॉग पिन 3 से जुड़ा है
int val = 0;         // चर मान को संग्रहीत करने के लिए

void setup() {
  pinMode(ledPin, OUTPUT);  // पिन को आउटपुट के रूप में सेट करता है
}

void loop() {
  val = analogRead(analogPin);  // इनपुट पिन पढ़ें
  analogWrite(ledPin, val / 4); // analogRead मान 0 से 1023 तक जाता है, analogWrite मान 0 से 255 तक
}
----
[%hardbreaks]


[float]
=== नोट्स और चेतावनी
PWM 5 और 6 पर जेनरेट किए गए आउटपुट में उच्च-अपेक्षा वाले ड्यूटी साइकल होंगे। यह `millis()` और `delay()` कार्यों के साथ बातचीत के कारण होता है, जो उन PWM आउटपुट उत्पन्न करने के लिए उपयोग किए जाने वाले एक ही आंतरिक टाइमर को साझा करते हैं। यह ज्यादातर कम शुल्क-चक्र सेटिंग्स (जैसे 0 - 10) पर देखा जाएगा और 0 और 6 पर पूरी तरह से आउटपुट बंद नहीं करने के परिणामस्वरूप 0 का मान हो सकता है।

--
// कैसे उपयोग करें खंड का अंत


// यह भी देखे खंड
[#see_also]
--

[float]
=== यह भी देखे

[role="language"]
* #भाषा# link:../../zero-due-mkr-family/analogwriteresolution[analogWriteResolution()]

[role="definition"]
* #परिभाषा# http://arduino.cc/en/Tutorial/PWM[PWM^]

[role="example"]
* #उदाहरण# http://arduino.cc/en/Tutorial/Blink[Blink^]

--
// यह भी देखे खंड का अंत
