---
title: analogRead()
categories: [ "कार्यों" ]
उपश्रेणियों: [ "एनालॉग आई/ओ" ]
---

= analogRead()

// अवलोकन अनुभाग शुरू होता है
[#अवलोकन]
--

[float]
=== विवरण
निर्दिष्ट एनालॉग पिन से मान पढ़ता है। आर्डुइनो बोर्डों में एक मल्टीचैनल, डिजिटल कनवर्टर के लिए 10-बिट एनालॉग होता है। इसका मतलब है कि यह 0 और 1023 के बीच पूर्णांक मानों में 0 और ऑपरेटिंग वोल्टेज (5V या 3.3V) के बीच इनपुट वोल्टेज को मैप करेगा। एक आर्डुइनो उनो (UNO) पर, उदाहरण के लिए, यह 5 वोल्ट / 1024 इकाइयों के रीडिंग के बीच एक रिज़ॉल्यूशन देता है। , 0.0049 वोल्ट (4.9 mV) प्रति यूनिट। प्रयोग करने योग्य पिन, ऑपरेटिंग वोल्टेज और कुछ आर्डुइनो बोर्डों के लिए अधिकतम रिज़ॉल्यूशन के लिए नीचे दी गई तालिका देखें।

इनपुट रेंज को link:../analogreference[analogReference()] का उपयोग करते हुए बदला जा सकता है, जबकि रिज़ॉल्यूशन को केवल link:../../zero-due-mkr-family/analogreadresolution[analogReadResolution()] का उपयोग करके बदला जा सकता है।.

ATmega आधारित बोर्ड (उनो (UNO), नैनो (Nano), मिनी (Mini), मेगा (Mega)) पर एनालॉग इनपुट को पढ़ने में लगभग 100 माइक्रोसेकंड (0.0001 सेकेंड) लगते हैं, इसलिए अधिकतम पढ़ने की दर लगभग 10,000 गुना दूसरी है|

[options="header"]
|===================================================
| बोर्ड                             | ऑपरेटिंग वोल्टेज | उपयोग करने योग्य पिन | अधिकतम संकल्प
| उनो (UNO)                       |5 वोल्ट         |A0 से A5            |10 बिट्स
| मिनी (Mini), नैनो (Nano)          |5 वोल्ट         |A0 से A7            |10 बिट्स
| मेगा (Mega), Mega2560, MegaADK   |5 वोल्ट         |A0 से A14           |10 बिट्स
| माइक्रो (Micro)                   |5 वोल्ट         |A0 से A11*          |10 बिट्स
| लेओनार्दो (Leonardo)              |5 वोल्ट         |A0 से A11*          |10 बिट्स
| जीरो (Zero)                     |3.3 वोल्ट       |A0 से A5            |12 बिट्स**
| ड्यू (Due)                       |3.3 वोल्ट       |A0 से A11           |12 बिट्स**
| एमकेआर (MKR) परिवार के बोर्ड्स     |3.3 वोल्ट       |A0 से A6            |12 बिट्स**
|===================================================

*A0 से A5 को बोर्ड पर लेबल किया गया है, A6 से  A11 क्रमशः पिन 4, 6, 8, 9, 10 और 12 पर उपलब्ध हैं| +
**इन बोर्डों के लिए डिफ़ॉल्ट analogRead() रिज़ॉल्यूशन संगतता के लिए 10 बिट्स है। इसे 12 बिट्स में बदलने के लिए आपको link:../../zero-due-mkr-family/analogreadresolution[analogReadResolution()] का उपयोग करने की आवश्यकता है|

[%hardbreaks]

[float]
=== वाक्य - विन्यास (Syntax)
`analogRead(pin)`


[float]
=== पैरामीटर
`pin`: एनालॉग इनपुट पिन का नाम ज्यादातर बोर्ड पर (A0 से A5, एमकेआर (MKR) बोर्डों पर A0 से A6, मिनी (Mini) और नैनो (Nano) पर A0 से A7, मेगा (Mega) पर A0 से A15 तक)|


[float]
=== रिटर्न
पिन पर एनालॉग रीडिंग। यद्यपि यह एनालॉग से डिजिटल कनवर्टर (10 बिट्स के लिए 0-1023 या 12 बिट्स के लिए 0-4095) के संकल्प तक सीमित है। डेटा प्रकार: `int`।

--
// ओवरव्यू अनुभाग अंत


// कैसे उपयोग करें खंड की शुरुआत
[#howtouse]
--

[float]
=== उदाहरण कोड
// वर्णन करें कि उदाहरण कोड क्या है और संबंधित कोड जोड़ें   ►►►►► यह खंड अनिवार्य है ◄◄◄◄◄
कोड analogPin पर वोल्टेज को पढ़ता है और इसे प्रदर्शित करता है।

[source,arduino]
----
int analogPin = A3; // पोटेंशियोमीटर वाइपर (मध्य टर्मिनल) एनालॉग पिन 3 से जुड़ा हुआ है
                    // बाहर ग्राउंड और 5 वोल्ट ओर जाता है
int val = 0;  // चर मान पढ़ने के स्टोर करने के लिए

void setup() {
  Serial.begin(9600);           //  सेटअप सीरियल
}

void loop() {
  val = analogRead(analogPin);  // इनपुट पिन पढ़ें
  Serial.println(val);          // डिबग मान
}
----
[%hardbreaks]

[float]
=== नोट्स और चेतावनी
यदि एनालॉग इनपुट पिन किसी भी चीज से जुड़ा नहीं है, तो analogRead() द्वारा लौटाए गए मान को कई कारकों के आधार पर उतार-चढ़ाव होगा (उदाहरण के लिए, अन्य एनालॉग इनपुट के मान, आपका हाथ बोर्ड के कितने करीब है, आदि)।

--
// कैसे उपयोग करें खंड का अंत


// यह भी देखे खंड
[#see_also]
--

[float]
=== यह भी देखे

[role="language"]
* #भाषा# link:../../zero-due-mkr-family/analogreadresolution[analogReadResolution()]
* #उदाहरण# http://arduino.cc/en/Tutorial/AnalogInputPins[एनालॉग इनपुट पिन का विवरण^]
--
// यह भी देखे खंड का अंत
