---
शीर्षक: analogWrite()
श्रेणियाँ: [ "कार्यों" ]
उपश्रेणियों: [ "एनालॉग आई/ओ" ]
---





= analogWrite()


// अवलोकन अनुभाग शुरू होता है
[#अवलोकन]
--

[float]
=== विवरण
एक पिन करने के लिए एक अनुरूप (http://arduino.cc/en/Tutorial/PWM[PWM wave]) मूल्य लिखता है। अलग-अलग चमक पर एक एलईडी प्रकाश करने या विभिन्न गति से मोटर चलाने के लिए इस्तेमाल किया जा सकता है। `analogWrite()` के लिए एक कॉल के बाद, अगली कॉल `analogWrite()` (या `digitalRead()` या `digitalWrite()`) के लिए अगली कॉल तक पिन निर्दिष्ट कर्तव्य चक्र की एक स्थिर वर्ग तरंग उत्पन्न करेगा। उसी पिन पर| 
[options="header"]
|====================================================================================================
| Board                | PWM Pins                        | PWM Frequency
| Uno, Nano, Mini      | 3, 5, 6, 9, 10, 11              | 490 Hz (pins 5 and 6: 980 Hz)
| Mega                 | 2 - 13, 44 - 46                 | 490 Hz (pins 4 and 13: 980 Hz)
| Leonardo, Micro, Yún | 3, 5, 6, 9, 10, 11, 13          | 490 Hz (pins 3 and 11: 980 Hz)
| Uno WiFi Rev.2       | 3, 5, 6, 9, 10                  | 976 Hz
| MKR boards *         | 0 - 8, 10, A3 (18), A4 (19)     | 732 Hz
| MKR1000 WiFi *       | 0 - 8, 10, 11, A3 (18), A4 (19) | 732 Hz
| Zero *               | 3 - 13, A0 (14), A1 (15)        | 732 Hz
| Due **               | 2-13                            | 1000 Hz
| 101                  | 3, 5, 6, 9                      | pins 3 and 9: 490 Hz, pins 5 and 6: 980 Hz
|====================================================================================================
{empty}* In addition to PWM capabilities on the pins noted above, the MKR and Zero boards have true analog output when using `analogWrite()` on the `DAC0` (`A0`) pin. +
{empty}** In addition to PWM capabilities on the pins noted above, the Due has true analog output when using `analogWrite()` on pins `DAC0` and `DAC1`.

[%hardbreaks]

You do not need to call `pinMode()` to set the pin as an output before calling `analogWrite()`.
The `analogWrite` function has nothing to do with the analog pins or the `analogRead` function.
[%hardbreaks]


[float]
=== Syntax
`analogWrite(pin, value)`


[float]
=== Parameters
`pin`: the Arduino pin to write to. Allowed data types: `int`. +
`value`: the duty cycle: between 0 (always off) and 255 (always on). Allowed data types: `int`.


[float]
=== रिटर्न
Nothing

--
// ओवरव्यू अनुभाग अंत




// कैसे उपयोग करें खंड की शुरुआत
[#howtouse]
--

[float]
=== उदाहरण कोड
पोटेंशियोमीटर से पढ़े जाने वाले मूल्य के लिए आनुपातिक एलईडी आउटपुट को सेट करता है|


[source,arduino]
----
int ledPin = 9;      // एलईडी डिजिटल पिन 9 से जुड़ा है
int analogPin = 3;   // पोटेंशियोमीटर एनालॉग पिन 3 से जुड़ा है
int val = 0;         // चर मान को संग्रहीत करने के लिए

void setup() {
  pinMode(ledPin, OUTPUT);  // पिन को आउटपुट के रूप में सेट करता है
}

void loop() {
  val = analogRead(analogPin);  // इनपुट पिन पढ़ें
  analogWrite(ledPin, val / 4); // analogRead मान 0 से 1023 तक जाता है, analogWrite मान 0 से 255 तक
}
----
[%hardbreaks]


[float]
=== Notes and Warnings
PWM 5 और 6 पर जेनरेट किए गए आउटपुट में उच्च-अपेक्षा वाले ड्यूटी साइकल होंगे। यह ` millis()` और `delay()` कार्यों के साथ बातचीत के कारण होता है, जो उन PWM आउटपुट उत्पन्न करने के लिए उपयोग किए जाने वाले एक ही आंतरिक टाइमर को साझा करते हैं। यह ज्यादातर कम शुल्क-चक्र सेटिंग्स (जैसे 0 - 10) पर देखा जाएगा और 0 और 6 पर पूरी तरह से आउटपुट बंद नहीं करने के परिणामस्वरूप 0 का मान हो सकता है।

--
// कैसे उपयोग करें खंड का अंत


// यह भी देखे खंड
[#see_also]
--

[float]
=== यह भी देखे

[role="language"]
* #भाषा# link:../../zero-due-mkr-family/analogwriteresolution[analogWriteResolution()]

[role="definition"]
* #परिभाषा# http://arduino.cc/en/Tutorial/PWM[PWM^]

[role="example"]
* #उदाहरण# http://arduino.cc/en/Tutorial/Blink[Blink^]

--
// यह भी देखे खंड का अंत
