---
title: analogReference()
categories: [ "कार्यों" ]
subCategories: [ "एनालॉग आई/ओ" ]
---


//


= analogReference()


// अवलोकन अनुभाग शुरू होता है
[#अवलोकन]
--

[float]
=== विवरण
एनालॉग इनपुट के लिए उपयोग किए जाने वाले संदर्भ वोल्टेज को कॉन्फ़िगर करता है (यानी इनपुट रेंज के शीर्ष के रूप में इस्तेमाल किया गया मूल्य)। विकल्प हैं:

आर्डुइनो AVR बोर्ड्स (उनो (UNO), मेगा (Mega), आदि)

* DEFAULT: 5 वोल्ट (5V आर्डुइनो बोर्ड पर) या 3.3 वोल्ट (3.3V आर्डुइनो बोर्ड पर) का डिफ़ॉल्ट एनालॉग संदर्भ|
* INTERNAL: एक निर्मित संदर्भ, ATmega168 या ATmega328P पर 1.1 वोल्ट के बराबर और ATmega8 पर 2.56 वोल्ट (आर्डुइनो मेगा (Mega) पर उपलब्ध नहीं)|
* INTERNAL1V1: एक अंतर्निहित 1.1V संदर्भ (केवल आर्डुइनो मेगा (Mega))|
* INTERNAL2V56: एक अंतर्निहित 2.56V संदर्भ (केवल आर्डुइनो मेगा (Mega))|
* EXTERNAL: AREF पिन (केवल 0 से 5V) पर लागू वोल्टेज को संदर्भ के रूप में उपयोग किया जाता है।

आर्डुइनो SAMD बोर्ड्स (जीरो (Zero), आदि)

* AR_DEFAULT: 3.3V का डिफ़ॉल्ट एनालॉग संदर्भ|
* AR_INTERNAL: एक अंतर्निहित 2.23V संदर्भ|
* AR_INTERNAL1V0: एक अंतर्निहित 1.0V संदर्भ|
* AR_INTERNAL1V65: एक अंतर्निहित 1.65V संदर्भ|
* AR_INTERNAL2V23: एक अंतर्निहित 2.23V संदर्भ|
* AR_EXTERNAL: AREF पिन पर लगाए गए वोल्टेज को संदर्भ के रूप में प्रयोग किया जाता है|

आर्डुइनो megaAVR बोर्ड्स (Uno WiFi Rev2)

* DEFAULT: एक अंतर्निर्मित 0.55V संदर्भ|
* INTERNAL: एक अंतर्निर्मित 0.55V संदर्भ|
* VDD: ATmega4809 का Vdd। Uno WiFi Rev2 पर 5V|
* INTERNAL0V55: एक अंतर्निर्मित 0.55V संदर्भ|
* INTERNAL1V1: एक अंतर्निर्मित 1.1V संदर्भ|
* INTERNAL1V5: एक अंतर्निर्मित 1.5V संदर्भ|
* INTERNAL2V5: एक अंतर्निर्मित 2.5V संदर्भ|
* INTERNAL4V3: एक अंतर्निर्मित 4.3V संदर्भ|
* EXTERNAL: AREF पिन (केवल 0 से 5V) पर लागू वोल्टेज को संदर्भ के रूप में उपयोग किया जाता है|

आर्डुइनो SAM बोर्ड्स (ड्यू)

* AR_DEFAULT: 3.3V का डिफ़ॉल्ट एनालॉग संदर्भ। यह ड्यू के लिए एकमात्र समर्थित विकल्प है।

[%hardbreaks]


[float]
=== वाक्य – विन्यास (Syntax)
`analogReference(type)`


[float]
=== पैरामीटर
`type`: किस प्रकार का संदर्भ उपयोग करना है (विवरण में विकल्पों की सूची देखें|


[float]
=== रिटर्न
Nothing

--
// ओवरव्यू अनुभाग अंत




// कैसे उपयोग करें खंड की शुरुआत
[#कैसेउपयोगकरें]
--

[float]
=== नोट्स और चेतावनी
एनालॉग संदर्भ को बदलने के बाद, `analogRead()` से पहले कुछ रीडिंग सटीक नहीं हो सकती हैं|

*AREF पर बाहरी संदर्भ वोल्टेज के लिए 0V से कम या 5V से अधिक का उपयोग न करें! यदि आप AREF पिन पर किसी बाहरी संदर्भ का उपयोग कर रहे हैं, तो आपको `analogRead()` कहने से पहले EXTERNAL पर एनालॉग संदर्भ सेट करना होगा।* अन्यथा, आप एक साथ सक्रिय संदर्भ वोल्टेज (आंतरिक रूप से उत्पन्न) और AREF पिन, संभवतः आपके अरुडिनो बोर्ड पर माइक्रोकंट्रोलर को नुकसान पहुंचाएंगे।

वैकल्पिक रूप से, आप बाहरी संदर्भ वोल्टेज को 5K प्रतिरोधक के माध्यम से AREF पिन से जोड़ सकते हैं, जिससे आप बाहरी और आंतरिक संदर्भ वोल्टेज के बीच स्विच कर सकते हैं. ध्यान दें कि प्रतिरोधक वोल्टेज को बदल देगा जो संदर्भ के रूप में उपयोग किया जाता है क्योंकि AREF पिन पर एक आंतरिक 32K प्रतिरोधक है। एक वोल्टेज विभक्त के रूप में दो कार्य करते हैं, इसलिए, उदाहरण के लिए, प्रतिरोधक के माध्यम से लागू 2.5V में AREF पिन पर 2.5 * 32 / (32 + 5) = ~2.2V का उत्पादन होगा|
[%hardbreaks]

--
// कैसे उपयोग करें खंड का अंत


// यह भी देखे खंड
[#यह_भी_देखे]
--

[float]
=== यह भी देखे

[role="example"]
* #उदाहरण# http://arduino.cc/en/Tutorial/AnalogInputPins[एनालॉग इनपुट पिन का विवरण^]

--
// यह भी देखे खंड का अंत
