---
title: const
categories: [ "चर" ]
subCategories: [ "चर स्कोप और क्वालिफायर" ]
---





= const keyword


// अवलोकन अनुभाग शुरू होता है
[#अवलोकन]
--

[float]
=== विवरण
`Const` कीवर्ड निरंतर के लिए खड़ा है। यह एक चर _qualifier_ है जो चर के व्यवहार को संशोधित करता है, जिससे एक चर "_read-only_" बनता है। इसका अर्थ है कि चर का उपयोग इसके प्रकार के किसी भी अन्य चर के रूप में किया जा सकता है, लेकिन इसके मूल्य को नहीं बदला जा सकता है। यदि आप `const` वैरिएबल के लिए मान निर्दिष्ट करने का प्रयास करते हैं तो आपको एक कंपाइलर त्रुटि मिलेगी।

`const` कीवर्ड के साथ परिभाषित कॉन्स्टैंट, link:../scope[वैरिएबल स्कोपिंग] के नियमों को मानते हैं जो अन्य वेरिएबल्स को नियंत्रित करते हैं। यह, और `#define` का उपयोग करने के नुकसान, `const` कीवर्ड को स्थिरांक को परिभाषित करने के लिए एक बेहतर विधि बनाता है और link:../../../structure/further-syntax/define[`#define`] का उपयोग करने पर अधिक पसंद किया जाता है।
[%hardbreaks]

--
// ओवरव्यू अनुभाग अंत




// कैसे उपयोग करें खंड की शुरुआत
[#कैसेउपयोगकरें]
--

[float]
=== उदाहरण कोड
// वर्णन करें कि उदाहरण कोड क्या है और संबंधित कोड जोड़ें   ►►►►► यह खंड अनिवार्य है ◄◄◄◄◄


[source,arduino]
----
const float pi = 3.14;
float x;
// ....
x = pi * 2; // गणित में consts का उपयोग करना ठीक है
pi = 7;     // अवैध - आप एक स्थिरांक को (संशोधित) नहीं लिख सकते
----
[%hardbreaks]

[float]
=== नोट्स और चेतावनी
*`#define` या `const`*

आप संख्यात्मक या स्ट्रिंग स्थिरांक बनाने के लिए या तो `const` या `#define` का उपयोग कर सकते हैं। link:../../data-types/array[सरणियों] के लिए, आपको `const` का उपयोग करने की आवश्यकता होगी। स्थिरांक को परिभाषित करने के लिए सामान्य रूप से `const` को `#define` से अधिक पसंद किया जाता है |


--
// कैसे उपयोग करें खंड का अंत


// यह भी देखे खंड
[#यह_भी_देखे]
--

[float]
=== यह भी देखे

[role="language"]
* #भाषा# link:../../../structure/further-syntax/define[#define]

--
// यह भी देखे खंड का अंत
