---
title: पूर्णांक लगातार
categories: [ "चर" ]
subCategories: [ "स्थिरांक" ]
---





= पूर्णांक लगातार


// अवलोकन अनुभाग शुरू होता है
[#अवलोकन]
--

[float]
=== Description
पूर्णांक स्थिरांक वे संख्याएँ होती हैं जिनका उपयोग सीधे स्केच में किया जाता है, जैसे 123। डिफ़ॉल्ट रूप से, इन संख्याओं को link:../../data-types/int[int] के रूप में माना जाता है लेकिन आप इसे U और L संशोधक के साथ बदल सकते हैं (निचे देखो)।
[%hardbreaks]

आम तौर पर, पूर्णांक स्थिरांक को आधार 10 (दशमलव) पूर्णांक के रूप में माना जाता है, लेकिन विशेष संकेतन (स्वरूपक) का उपयोग अन्य आधारों में संख्या दर्ज करने के लिए किया जा सकता है।
[%hardbreaks]

|===
| आधार | उदाहरण | प्रारूप | टिप्पणी |

|10 (दशमलव)
|123
|none
|

|2 (बाइनरी)
|B1111011
|प्रमुख 'B'
|केवल 8 बिट मूल्यों के साथ काम करता है (0 to 255)   वर्ण 0&1 मान्य

|8 (अष्टक)
|0173
|प्रमुख "0"
|वर्ण 0-7 वैध

|16 (हेक्साडेसिमल)
|0x7B
|प्रमुख "0x"
|वर्ण 0-9, A-F, a-f वैध
|===
[%hardbreaks]

--
// ओवरव्यू अनुभाग अंत



// कैसे उपयोग करें खंड की शुरुआत
[#कैसेउपयोगकरें]
--
[float]
== दशमलव (आधार 10)
यह सामान्य ज्ञान का गणित है जिससे आप परिचित हैं। अन्य उपसर्गों के बिना स्थिरांक को दशमलव प्रारूप में माना जाता है।

[float]
=== उदाहरण कोड:
[source,arduino]
----
n = 101;  // 101 दशमलव के समान ((1 * 10^2) + (0 * 10^1) + 1)
----
[%hardbreaks]

[float]
== बाइनरी (बेस 2)
केवल वर्ण 0 और 1 ही मान्य हैं।

[float]
=== उदाहरण कोड:
[source,arduino]
----
n = B101; // 5 दशमलव के समान ((1 * 2^2) + (0 * 2^1) + 1)
----

बाइनरी फॉर्मैटर केवल 0 (B0) और 255 (B11111111) के बीच बाइट्स (8 बिट्स) पर काम करता है। यदि द्विआधारी रूप में एक इंट (16 बिट्स) इनपुट करना सुविधाजनक है, तो आप इसे दो-चरणीय प्रक्रिया जैसे:
[source,arduino]
----
myInt = (B11001100 * 256) + B10101010;  // B11001100 हाई बाइट है`
----
[%hardbreaks]

[float]
== अष्टक (आधार 8)
केवल 7 के माध्यम से 0 अक्षर मान्य हैं। अष्ट मानों को उपसर्ग "0" (शून्य) द्वारा इंगित किया जाता है।

[float]
=== उदाहरण कोड:
[source,arduino]
----
n = 0101; // 65 दशमलव के समान ((1 * 8^2) + (0 * 8^1) + 1)
----
यह एक निरंतर से पहले एक अग्रणी शून्य सहित (अनजाने में) एक कठिन-से-बग को उत्पन्न करना संभव है और संकलक अनजाने में अपने स्थिरांक को अष्टक के रूप में व्याख्या करता है।
[%hardbreaks]

[float]
== हेक्साडेसिमल (बेस 16)
वैध वर्ण 0 से 9 होते हैं और अक्षर A से F; A का मान 10 है, B 11 है, F तक, जो 15. है। हेक्स मूल्यों को उपसर्ग "0x" द्वारा दर्शाया गया है। ध्यान दें कि A-F ऊपरी (A-F) या निचला मामला (a-f) हो सकता है।

[float]
=== उदाहरण कोड:
[source,arduino]
----
n = 0x101;  // 257 दशमलव के समान ((1 * 16^2) + (0 * 16^1) + 1)
----
[%hardbreaks]


[float]
=== नोट्स और चेतावनी
*U एंड L फॉर्मेटर्स:*

डिफ़ॉल्ट रूप से, पूर्णांक स्थिरांक को मानों में परिचर सीमाओं के साथ एक इंट के रूप में माना जाता है। किसी अन्य डेटा प्रकार के साथ पूर्णांक स्थिरांक निर्दिष्ट करने के लिए, इसका अनुसरण करें:

  - एक 'u' या 'U' निरंतर को एक अहस्ताक्षरित डेटा प्रारूप में मजबूर करने के लिए। उदाहरण: 33u
  - एक 'l' या 'L' निरंतर को एक लंबे डेटा प्रारूप में मजबूर करने के लिए। उदाहरण: 100000L
  - एक 'ul' या 'UL' एक निरंतर लंबे समय में स्थिर करने के लिए मजबूर करने के लिए। उदाहरण: 32767ul

[%hardbreaks]

--
// कैसे उपयोग करें खंड का अंत




// यह भी देखे खंड
[#यह_भी_देखे]
--

[float]
=== यह भी देखे

[role="language"]

--
// यह भी देखे खंड का अंत
